ejercicio/urls.py
from django.conf.urls import url, include

from base.views import index, configurar, datos_configuracion

# Conexion de las URLs con las funciones de las vistas
urlpatterns = [
    url(r'^$', index),
    url(r'^datos/$', datos_configuracion),
    url(r'configurar/' +
        '(?P<tasa_interes>([0-9]+\.)?[0-9]+)/' +
        '(?P<porcentaje_enganche>([0-9]+\.)?[0-9]+)$',
        configurar),
    url(r'^clientes/', include('clientes.urls')),
    url(r'^productos/', include('productos.urls')),
    url(r'^ventas/', include('ventas.urls')),
]

ventas/urls.py
from django.conf.urls import url

import views

# Conexion de los URLs con las funciones de las vistas
urlpatterns = [
    url(r'^$', views.venta),
]

clientes/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models


class Cliente(models.Model):
    """Clase Cliente con los campos de su tabla"""
    nombre = models.CharField(u"Nombre", max_length=200, blank=False, null=False)
    direccion = models.CharField(u"Dirección", max_length=300, blank=False, null=False)
    ciudad = models.CharField(u"Ciudad", max_length=50, blank=False, null=False)
    estado = models.CharField(u"Estado", max_length=50, blank=False, null=False)
    rfc = models.CharField(u"RFC", max_length=13, blank=False, null=False)

    def __str__(self):
        """ Cadena que se muestra en las querys  """
        return self.nombre

ventas/views.py
from django.shortcuts import render_to_response, redirect
from django.template.context_processors import csrf
from django.core import serializers
from django.http import HttpResponse

from clientes.models import Cliente
from productos.models import Producto
from base.views import configuracion


def venta(request):
    """ Vista para hacer las ventas """
    # Diccionario que se pasa a la plantilla con las variables que se necesiten
    contexto = {'opcion': 'Ventas'}
    contexto.update(csrf(request))
    contexto.update(configuracion())
    # Query con la lista de empleados
    contexto['clientes'] = Cliente.objects.all()
    contexto['productos'] = Producto.objects.all()

    return render_to_response("ventas/venta.html", contexto)

ventas/templates/ventas/venta.html
{% extends "base/base.html" %}
{% load staticfiles %}
{% load bootstrap %}

{% block content %}

<form method="POST" action="/ventas/nueva" enctype="multipart/form-data" accept-charset="UTF-8" role="form"> {% csrf_token %}

<div class="row">
  <div class="form-group">
    <label class="control-label col-xs-1" for="id_cliente">Cliente</label>
    <div class="col-xs-8">
      <select class="form-control" id="id_cliente">
        <option value="0"></option>
        {% for cliente in clientes %}
          <option value="{{cliente.id}}">{{cliente}}</option>
        {% endfor %}
      </select>
    </div>
    <label class="control-label col-xs-1" for="id_folio">Folio</label>
    <div class="col-xs-2">
      <input type="number" value="456" class="form-control" id="id_folio" disabled></input>
    </div>
    <div class="col-xs-9">
      <input type="text" class="form-control" id="id_direccion" disabled></input>
    </div>
    <label class="control-label col-xs-1" for="id_fecha">Fecha</label>
    <div class="col-xs-2">
      <input type="text" value="{% now 'd/m/Y' %}" class="form-control" id="id_fecha" disabled></input>
    </div>
    <div class="col-xs-9">
      <input type="text" class="form-control" id="id_ciudad" disabled></input>
    </div>
    <label class="control-label col-xs-1" for="id_rfc">RFC</label>
    <div class="col-xs-2">
      <input type="text" value="" class="form-control" id="id_rfc" disabled></input>
    </div>
  </div>
</div>

<div class="row" style="margin-top: 20px;">
  <div class="form-group">
    <label class="control-label col-xs-1" for="id_producto">Producto</label>  
    <div class="col-xs-7">
      <select id="id_producto" class="form-control">
        <option value="0"></option>
        {% for producto in productos %}
          <option value="{{producto.id}}">{{producto}}</option> 
        {% endfor %}
      </select>
    </div>
    <div class="col-xs-2">
      <input type="number" name="cantidad" class="form-control" id="id_cantidad" placeholder="Cantidad" min="1" max="9999"></input>
    </div>
    <div class="col-xs-2">
      <button class="btn btn-info" id="id_agregar">Agregar</button>
    </div>
</div>
</div>

<div class="row" style="margin-top: 20px;">
  <div class="col-xs-12">
    <div class="box">
      <div class="box-header"><h3 class="box-title">Detalle de la compra</h3></div>
      <div class="box-body table-responsive no-padding">
        <table class="table table-hover">
          <tbody id="tabla">
            <tr data-id="0">
              <th>Descripción del artículo</th>
              <th>Modelo</th>
              <th>Cantidad</th>
              <th>Precio</th>
              <th>Importe</th>
              <th style="width: 20px;"></th>
            </tr>
          </tbody>
        </table>
      </div>
    </div> 
  </div>
</div>

<div class="row" style="margin-top: 10px;">
  <div class="form-group">
    <label for="id_enganche" class="control-label col-xs-10" style="text-align: right;">Enganche</label>
    <div class="col-xs-2">
      <input id="id_enganche" type="number" class="form-control" min="1" max="999999"></input>
    </div>
    <label for="id_bonificacion" class="control-label col-xs-10" style="text-align: right;">Bonificación enganche</label>
    <div class="col-xs-2">
      <input id="id_bonificacion" type="number" class="form-control" disabled></input>
    </div>
    <label for="id_total" class="control-label col-xs-10" style="text-align: right;">Total Adeudo</label>
    <div class="col-xs-2">
      <input id="id_adeudo" type="number" class="form-control" disabled></input>
    </div>
  </div>
</div>

<div class="row" style="margin-top: 10px;">
  <div class="col-xs-12">
    <div class="box">
      <div class="box-header"><h3 class="box-title">Abonos Mensuales</h3></div>
      <div class="box-body table-responsive no-padding">
        <table class="table table-hover">
          <tbody id="tabla_abonos">
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

</form>

    
{% endblock content %}

{% block jsextra %}
  var tasa_interes = {{tasa_interes}};
  <script src="{% static "js/ventas.js" %}"></script>
{% endblock jsextra %}